### ISSUE TITLE
Tiktok link

### ISSUE THREAD

**Issue by Walkoud** [MOHAMMAD-NAYAN/nayan-media-downloader#7]
This kind of link not working : https://vm.tiktok.com/ZGeTo7tHd/
but this link is the same : https://www.tiktok.com/@yxss13/video/7409433566771203361?_r=1&_t=8pMHl5uJHxB 
and its working

You know what to do

**Comment by MOHAMMAD-NAYAN** [comment]
Update your tiktok app 

If you update your tiktok app then your  tiktok link change and working
